/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ProductManagement.Product;
import model.ProductManagement.ProductCatalog;
import model.Supplier.Supplier;
import model.Supplier.SupplierDirectory;


/**
 *
 * @author xiaokunchen
 */
public class reportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form reportJPanel
     */
    private final SupplierDirectory supplierDirectory;
    private final ProductCatalog productCatalog;
    
    public reportJPanel(JPanel workPanel) {
        spList.initializeData();
        this.supplierDirectory = spList.getSupplierDirectory();
        this.productCatalog = spList.getProductCatalog();
        initComponents();
        populateSupplierComboBox();
    }
    
    private void populateSupplierComboBox() {
        cmbSupplier.removeAllItems();
        
        for (Supplier supplier : supplierDirectory.getSupplierList()) {
            cmbSupplier.addItem(supplier.getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        cmbSupplier = new javax.swing.JComboBox<>();
        lblSupplier = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Revenue", "Sales", "Target Price", "Caost Price", "Fixed Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReport);

        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        lblSupplier.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplier.setText("Choose Supplier:");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnView)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSupplier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplier))
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

       DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
    model.setRowCount(0); 

    String selectedSupplierName = (String) cmbSupplier.getSelectedItem();

    if (selectedSupplierName != null) {
        Supplier selectedSupplier = null;

        for (Supplier supplier : supplierDirectory.getSupplierList()) {
            if (supplier.getName().equals(selectedSupplierName)) {
                selectedSupplier = supplier;
                break;
            }
        }

        if (selectedSupplier != null) {
            int supplierIndex = supplierDirectory.getSupplierList().indexOf(selectedSupplier);
            int startIndex = supplierIndex * 10;
            int endIndex = Math.min(startIndex + 10, productCatalog.getProductList().size()); 

            for (int i = startIndex; i < endIndex; i++) {
                Product product = productCatalog.getProductList().get(i);
                model.addRow(new Object[]{
                    product.getName(),
                    product.getRevenue(),      
                    product.getAvailability(),
                    product.getTargetPrice(),
                    product.getCostPrice(),
                    product.getFixedPrice()
                });
            }
        }
    }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<Object> cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables



}
